namespace PowerOffScreensaver.Localization;

public record LangStrings(
    string Flag,
    string NativeName,
    string WindowTitle,
    string LockOnExit,
    string DdcCi,
    string DelayMs,
    string TestBtn,
    string OkBtn,
    string CancelBtn,
    string LangLabel,
    string VersionPrefix,
    string CheckBtn,
    string DiagTitle,
    string DiagAllPass,
    string DiagSomeFail,
    string DiagRunNow,
    string DiagClose,
    string LockOnExitHint,
    string DelayHint,
    string DdcCiHint,
    string InstallBtn,
    string InstallOffer,
    string InstallDoneFmt,
    string InstallRemovedFmt,
    string InstallFailedFmt,
    string InstallCheckName,
    string StatusInstalledFmt,
    string StatusNotInstalled,
    string PowerMethodLabel,
    string ModeAuto,
    string ModeDdcCi,
    string ModeDpms,
    string ModeBoth,
    string TestMonitorsBtn,
    string TestTitle,
    string TestIntro,
    string TestRunBtn,
    string ColMonitor,
    string ColDdc,
    string ColResult,
    string ResultOff,
    string ResultOn,
    string ResultUnknown,
    string TestHint,
    string ModeNone,
    string TestConfirmQuestion,
    string TestMonitorCountdown,
    string TestMonitorHeaderFmt,
    string TestPerMonitorConfirmFmt
);

public static class Strings
{
    private static string _lang = "en";

    public static void Set(string lang) =>
        _lang = All.ContainsKey(lang) ? lang : "en";

    public static string Current => _lang;

    public static LangStrings Get(string? lang = null) =>
        All.TryGetValue(lang ?? _lang, out var s) ? s : All["en"];

    public static readonly IReadOnlyDictionary<string, LangStrings> All =
        new Dictionary<string, LangStrings>
        {
            ["en"] = new(
                "🇬🇧", "English",
                "PowerOffScreensaver {0} — Settings",
                "Lock workstation on exit",
                "Try DDC/CI monitor power-off (experimental)",
                "Power-off delay (ms):",
                "Test", "OK", "Cancel", "Language:", "Version",
                "Check System",
                "BOSS — System Check",
                "✓  All checks passed — BOSS is ready.",
                "✗  Some checks failed. See details above.",
                "Run Screensaver",
                "Close",
                "When the screensaver is dismissed, lock Windows so a password is required to return.",
                "How long the screen stays black before the monitors are powered off.",
                "Experimental: ask monitors to power off via DDC/CI. Leave off if unsure.",
                "Install into Windows",
                "Set Blackout ScreenSaver as your active Windows screensaver?",
                "Installed v{0} as your active screensaver.",
                "Removed {0} old version(s).",
                "Install failed: {0}",
                "Installation",
                "v{0} installed and active",
                "Not installed",
                "Monitor power-off method:",
                "Auto (recommended)",
                "DDC/CI (per monitor)",
                "DPMS (system)",
                "Both (DDC/CI + DPMS)",
                "Test monitors…",
                "Monitor power-off test",
                "Turns each monitor off for a few seconds, then back on. Watch which screens actually go dark.",
                "Run test",
                "Monitor",
                "DDC/CI",
                "Result",
                "Turned off",
                "Stayed on",
                "Unknown",
                "If a monitor stays on, pick 'Both', or enable DDC/CI in that monitor's on-screen menu.",
                "Black screen only (no power-off)",
                "Did it work correctly? Did every monitor go dark and then come back on?",
                "This monitor will go dark now",
                "Monitor {0} of {1}",
                "Monitor {0}: did it go dark and then come back on correctly?"
            ),
            ["ru"] = new(
                "🇷🇺", "Русский",
                "PowerOffScreensaver {0} — Параметры",
                "Блокировать рабочую станцию при выходе",
                "Попробовать DDC/CI выключение мониторов (эксперим.)",
                "Задержка перед отключением (мс):",
                "Тест", "ОК", "Отмена", "Язык:", "Версия",
                "Проверить",
                "BOSS — Проверка системы",
                "✓  Все проверки пройдены — BOSS готов к работе.",
                "✗  Некоторые проверки не пройдены. Смотрите выше.",
                "Запустить",
                "Закрыть",
                "При выходе из заставки блокирует Windows — для возврата потребуется пароль.",
                "Сколько экран остаётся чёрным до отключения мониторов.",
                "Эксперимент: выключение мониторов через DDC/CI. Оставьте выключенным, если не уверены.",
                "Установить в Windows",
                "Сделать Blackout ScreenSaver активной заставкой Windows?",
                "Установлена версия v{0} как активная заставка.",
                "Удалено старых версий: {0}.",
                "Ошибка установки: {0}",
                "Установка",
                "v{0} установлена и активна",
                "Не установлена",
                "Метод отключения мониторов:",
                "Авто (рекомендуется)",
                "DDC/CI (каждый монитор)",
                "DPMS (системно)",
                "Оба (DDC/CI + DPMS)",
                "Тест мониторов…",
                "Тест отключения мониторов",
                "Выключает каждый монитор на несколько секунд, затем включает. Посмотрите, какие экраны реально гаснут.",
                "Запустить тест",
                "Монитор",
                "DDC/CI",
                "Результат",
                "Погас",
                "Остался включён",
                "Неизвестно",
                "Если монитор не гаснет, выберите «Оба» или включите DDC/CI в экранном меню этого монитора.",
                "Только чёрный экран (без выключения)",
                "Всё отработало правильно? Каждый монитор погас, а затем снова включился?",
                "Сейчас данный монитор погаснет",
                "Монитор {0} из {1}",
                "Монитор {0}: он корректно погас, а затем снова включился?"
            ),
            ["de"] = new(
                "🇩🇪", "Deutsch",
                "PowerOffScreensaver {0} — Einstellungen",
                "Arbeitsstation beim Beenden sperren",
                "DDC/CI-Abschaltung versuchen (experimentell)",
                "Abschaltverzögerung (ms):",
                "Test", "OK", "Abbrechen", "Sprache:", "Version",
                "Prüfen",
                "BOSS — Systemprüfung",
                "✓  Alle Tests bestanden — BOSS ist bereit.",
                "✗  Einige Tests fehlgeschlagen. Siehe Details oben.",
                "Starten",
                "Schließen",
                "Sperrt Windows beim Beenden des Bildschirmschoners; zur Rückkehr ist ein Passwort nötig.",
                "Wie lange der Bildschirm schwarz bleibt, bevor die Monitore abgeschaltet werden.",
                "Experimentell: Monitore per DDC/CI abschalten. Im Zweifel deaktiviert lassen.",
                "In Windows installieren",
                "Blackout ScreenSaver als aktiven Windows-Bildschirmschoner festlegen?",
                "Version v{0} als aktiver Bildschirmschoner installiert.",
                "{0} alte Version(en) entfernt.",
                "Installation fehlgeschlagen: {0}",
                "Installation",
                "v{0} installiert und aktiv",
                "Nicht installiert",
                "Monitor-Abschaltmethode:",
                "Auto (empfohlen)",
                "DDC/CI (pro Monitor)",
                "DPMS (System)",
                "Beide (DDC/CI + DPMS)",
                "Monitore testen…",
                "Monitor-Abschalttest",
                "Schaltet jeden Monitor einige Sekunden aus und wieder ein. Beobachten Sie, welche Bildschirme wirklich dunkel werden.",
                "Test starten",
                "Monitor",
                "DDC/CI",
                "Ergebnis",
                "Ausgeschaltet",
                "Blieb an",
                "Unbekannt",
                "Bleibt ein Monitor an, wählen Sie „Beide“ oder aktivieren Sie DDC/CI im Bildschirmmenü des Monitors.",
                "Nur schwarzer Bildschirm (kein Abschalten)",
                "Hat alles korrekt funktioniert? Wurde jeder Monitor dunkel und ging dann wieder an?",
                "Dieser Monitor wird jetzt dunkel",
                "Monitor {0} von {1}",
                "Monitor {0}: Wurde er dunkel und ging dann korrekt wieder an?"
            ),
            ["fr"] = new(
                "🇫🇷", "Français",
                "PowerOffScreensaver {0} — Paramètres",
                "Verrouiller la session à la sortie",
                "Essayer l'extinction DDC/CI (expérimental)",
                "Délai avant extinction (ms) :",
                "Test", "OK", "Annuler", "Langue :", "Version",
                "Vérifier",
                "BOSS — Vérification système",
                "✓  Tous les tests réussis — BOSS est prêt.",
                "✗  Certains tests ont échoué. Voir les détails ci-dessus.",
                "Lancer",
                "Fermer",
                "À la sortie de l'écran de veille, verrouille Windows ; un mot de passe sera requis.",
                "Durée pendant laquelle l'écran reste noir avant l'extinction des moniteurs.",
                "Expérimental : éteindre les moniteurs via DDC/CI. Laissez désactivé en cas de doute.",
                "Installer dans Windows",
                "Définir Blackout ScreenSaver comme écran de veille actif de Windows ?",
                "Version v{0} installée comme écran de veille actif.",
                "{0} ancienne(s) version(s) supprimée(s).",
                "Échec de l'installation : {0}",
                "Installation",
                "v{0} installé et actif",
                "Non installé",
                "Méthode d'extinction des moniteurs :",
                "Auto (recommandé)",
                "DDC/CI (par moniteur)",
                "DPMS (système)",
                "Les deux (DDC/CI + DPMS)",
                "Tester les moniteurs…",
                "Test d'extinction des moniteurs",
                "Éteint chaque moniteur quelques secondes, puis le rallume. Observez quels écrans s'éteignent vraiment.",
                "Lancer le test",
                "Moniteur",
                "DDC/CI",
                "Résultat",
                "Éteint",
                "Resté allumé",
                "Inconnu",
                "Si un moniteur reste allumé, choisissez « Les deux » ou activez le DDC/CI dans le menu du moniteur.",
                "Écran noir seulement (sans extinction)",
                "Tout a bien fonctionné ? Chaque moniteur s'est-il éteint puis rallumé ?",
                "Ce moniteur va s'éteindre maintenant",
                "Moniteur {0} sur {1}",
                "Moniteur {0} : s'est-il éteint puis rallumé correctement ?"
            ),
            ["es"] = new(
                "🇪🇸", "Español",
                "PowerOffScreensaver {0} — Configuración",
                "Bloquear equipo al salir",
                "Intentar apagado DDC/CI (experimental)",
                "Retraso de apagado (ms):",
                "Probar", "OK", "Cancelar", "Idioma:", "Versión",
                "Verificar",
                "BOSS — Verificación del sistema",
                "✓  Todas las pruebas superadas — BOSS listo.",
                "✗  Algunas pruebas fallaron. Ver detalles arriba.",
                "Iniciar",
                "Cerrar",
                "Al salir del salvapantallas, bloquea Windows; se pedirá contraseña para volver.",
                "Cuánto tiempo la pantalla permanece en negro antes de apagar los monitores.",
                "Experimental: apagar monitores mediante DDC/CI. Déjelo desactivado si no está seguro.",
                "Instalar en Windows",
                "¿Establecer Blackout ScreenSaver como salvapantallas activo de Windows?",
                "Versión v{0} instalada como salvapantallas activo.",
                "Se eliminaron {0} versión(es) antigua(s).",
                "Error de instalación: {0}",
                "Instalación",
                "v{0} instalado y activo",
                "No instalado",
                "Método de apagado de monitores:",
                "Auto (recomendado)",
                "DDC/CI (por monitor)",
                "DPMS (sistema)",
                "Ambos (DDC/CI + DPMS)",
                "Probar monitores…",
                "Prueba de apagado de monitores",
                "Apaga cada monitor unos segundos y luego lo enciende. Observe qué pantallas se apagan de verdad.",
                "Ejecutar prueba",
                "Monitor",
                "DDC/CI",
                "Resultado",
                "Apagado",
                "Siguió encendido",
                "Desconocido",
                "Si un monitor sigue encendido, elija «Ambos» o active DDC/CI en el menú del monitor.",
                "Solo pantalla negra (sin apagado)",
                "¿Funcionó todo bien? ¿Cada monitor se apagó y luego volvió a encenderse?",
                "Este monitor se apagará ahora",
                "Monitor {0} de {1}",
                "Monitor {0}: ¿se apagó y luego volvió a encenderse correctamente?"
            ),
            ["it"] = new(
                "🇮🇹", "Italiano",
                "PowerOffScreensaver {0} — Impostazioni",
                "Blocca la workstation all'uscita",
                "Prova spegnimento DDC/CI (sperimentale)",
                "Ritardo spegnimento (ms):",
                "Test", "OK", "Annulla", "Lingua:", "Versione",
                "Verifica",
                "BOSS — Verifica sistema",
                "✓  Tutti i test superati — BOSS è pronto.",
                "✗  Alcuni test falliti. Vedere i dettagli sopra.",
                "Avvia",
                "Chiudi",
                "All'uscita dal salvaschermo blocca Windows; per tornare sarà richiesta la password.",
                "Per quanto tempo lo schermo resta nero prima di spegnere i monitor.",
                "Sperimentale: spegnere i monitor tramite DDC/CI. Lascia disattivato in caso di dubbio.",
                "Installa in Windows",
                "Impostare Blackout ScreenSaver come salvaschermo attivo di Windows?",
                "Versione v{0} installata come salvaschermo attivo.",
                "Rimosse {0} vecchia/e versione/i.",
                "Installazione non riuscita: {0}",
                "Installazione",
                "v{0} installato e attivo",
                "Non installato",
                "Metodo di spegnimento monitor:",
                "Auto (consigliato)",
                "DDC/CI (per monitor)",
                "DPMS (sistema)",
                "Entrambi (DDC/CI + DPMS)",
                "Prova monitor…",
                "Prova di spegnimento monitor",
                "Spegne ogni monitor per alcuni secondi, poi lo riaccende. Osserva quali schermi si spengono davvero.",
                "Avvia prova",
                "Monitor",
                "DDC/CI",
                "Risultato",
                "Spento",
                "Rimasto acceso",
                "Sconosciuto",
                "Se un monitor resta acceso, scegli «Entrambi» o abilita il DDC/CI nel menu del monitor.",
                "Solo schermo nero (senza spegnimento)",
                "Ha funzionato tutto correttamente? Ogni monitor si è spento e poi riacceso?",
                "Questo monitor si spegnerà ora",
                "Monitor {0} di {1}",
                "Monitor {0}: si è spento e poi riacceso correttamente?"
            ),
            ["pt"] = new(
                "🇵🇹", "Português",
                "PowerOffScreensaver {0} — Configurações",
                "Bloquear workstation ao sair",
                "Tentar desligar DDC/CI (experimental)",
                "Atraso de desligamento (ms):",
                "Testar", "OK", "Cancelar", "Idioma:", "Versão",
                "Verificar",
                "BOSS — Verificação do sistema",
                "✓  Todos os testes passaram — BOSS está pronto.",
                "✗  Alguns testes falharam. Veja detalhes acima.",
                "Iniciar",
                "Fechar",
                "Ao sair da proteção de tela, bloqueia o Windows; será pedida senha para voltar.",
                "Quanto tempo a tela fica preta antes de os monitores serem desligados.",
                "Experimental: desligar monitores via DDC/CI. Deixe desativado se não tiver certeza.",
                "Instalar no Windows",
                "Definir Blackout ScreenSaver como proteção de tela ativa do Windows?",
                "Versão v{0} instalada como proteção de tela ativa.",
                "{0} versão(ões) antiga(s) removida(s).",
                "Falha na instalação: {0}",
                "Instalação",
                "v{0} instalada e ativa",
                "Não instalada",
                "Método de desligamento dos monitores:",
                "Auto (recomendado)",
                "DDC/CI (por monitor)",
                "DPMS (sistema)",
                "Ambos (DDC/CI + DPMS)",
                "Testar monitores…",
                "Teste de desligamento dos monitores",
                "Desliga cada monitor por alguns segundos e liga de novo. Observe quais telas realmente escurecem.",
                "Executar teste",
                "Monitor",
                "DDC/CI",
                "Resultado",
                "Desligou",
                "Continuou ligado",
                "Desconhecido",
                "Se um monitor continuar ligado, escolha «Ambos» ou ative o DDC/CI no menu do monitor.",
                "Apenas tela preta (sem desligar)",
                "Funcionou corretamente? Cada monitor escureceu e depois voltou a ligar?",
                "Este monitor vai apagar agora",
                "Monitor {0} de {1}",
                "Monitor {0}: escureceu e depois voltou a ligar corretamente?"
            ),
            ["pl"] = new(
                "🇵🇱", "Polski",
                "PowerOffScreensaver {0} — Ustawienia",
                "Zablokuj stację roboczą przy wyjściu",
                "Wypróbuj wyłączanie DDC/CI (eksperymentalne)",
                "Opóźnienie wyłączenia (ms):",
                "Test", "OK", "Anuluj", "Język:", "Wersja",
                "Sprawdź",
                "BOSS — Sprawdzanie systemu",
                "✓  Wszystkie testy zaliczone — BOSS jest gotowy.",
                "✗  Niektóre testy nie powiodły się. Patrz szczegóły.",
                "Uruchom",
                "Zamknij",
                "Po zamknięciu wygaszacza blokuje Windows; do powrotu wymagane będzie hasło.",
                "Jak długo ekran pozostaje czarny, zanim monitory zostaną wyłączone.",
                "Eksperymentalne: wyłączanie monitorów przez DDC/CI. W razie wątpliwości pozostaw wyłączone.",
                "Zainstaluj w Windows",
                "Ustawić Blackout ScreenSaver jako aktywny wygaszacz ekranu Windows?",
                "Zainstalowano wersję v{0} jako aktywny wygaszacz.",
                "Usunięto starych wersji: {0}.",
                "Instalacja nie powiodła się: {0}",
                "Instalacja",
                "v{0} zainstalowana i aktywna",
                "Nie zainstalowano",
                "Metoda wyłączania monitorów:",
                "Auto (zalecane)",
                "DDC/CI (każdy monitor)",
                "DPMS (systemowo)",
                "Oba (DDC/CI + DPMS)",
                "Testuj monitory…",
                "Test wyłączania monitorów",
                "Wyłącza każdy monitor na kilka sekund, potem włącza. Zobacz, które ekrany naprawdę gasną.",
                "Uruchom test",
                "Monitor",
                "DDC/CI",
                "Wynik",
                "Zgaszony",
                "Pozostał włączony",
                "Nieznany",
                "Jeśli monitor pozostaje włączony, wybierz „Oba” lub włącz DDC/CI w menu monitora.",
                "Tylko czarny ekran (bez wyłączania)",
                "Czy wszystko zadziałało poprawnie? Czy każdy monitor zgasł, a potem znów się włączył?",
                "Ten monitor zaraz zgaśnie",
                "Monitor {0} z {1}",
                "Monitor {0}: czy zgasł, a potem poprawnie się włączył?"
            ),
            ["zh"] = new(
                "🇨🇳", "中文",
                "PowerOffScreensaver {0} — 设置",
                "退出时锁定工作站",
                "尝试通过 DDC/CI 关闭显示器（实验性）",
                "关闭延迟（毫秒）：",
                "测试", "确定", "取消", "语言：", "版本",
                "检查系统",
                "BOSS — 系统检查",
                "✓  所有检查通过 — BOSS 已就绪。",
                "✗  部分检查未通过。请查看上方详情。",
                "运行屏保",
                "关闭",
                "退出屏保时锁定 Windows，返回时需要输入密码。",
                "在关闭显示器之前，屏幕保持黑色的时长。",
                "实验性：通过 DDC/CI 关闭显示器。如不确定请保持关闭。",
                "安装到 Windows",
                "将 Blackout ScreenSaver 设为 Windows 当前屏幕保护程序？",
                "已安装 v{0} 并设为当前屏幕保护程序。",
                "已移除 {0} 个旧版本。",
                "安装失败：{0}",
                "安装",
                "v{0} 已安装并启用",
                "未安装",
                "显示器关闭方式：",
                "自动（推荐）",
                "DDC/CI（逐个显示器）",
                "DPMS（系统）",
                "两者（DDC/CI + DPMS）",
                "测试显示器…",
                "显示器关闭测试",
                "将每台显示器关闭几秒后再打开。观察哪些屏幕真正熄灭。",
                "开始测试",
                "显示器",
                "DDC/CI",
                "结果",
                "已关闭",
                "仍亮着",
                "未知",
                "如果某台显示器仍亮着，请选择“两者”，或在该显示器的屏幕菜单中启用 DDC/CI。",
                "仅黑屏（不关闭显示器）",
                "一切正常吗？每台显示器是否先熄灭然后又重新亮起？",
                "此显示器即将熄灭",
                "显示器 {0} / {1}",
                "显示器 {0}：它是否先熄灭然后又正确亮起？"
            ),
        };
}
